language: node_js
sudo: false
node_js:
- '7'

branches:
  only:
  - master

deploy:
  provider: heroku
  api_key:
    secure: b9ec777b-f764-4ff1-abc5-55ef220ecdef
  app: vue-address-app
  on:
    repo: vladpereskokov/vue-address-app
    branch: master
  skip_cleanup: true

before_script:
  - npm install

script:
  - npm run codeStyle
  - npm run webpack
